export const GET_LIST_REQUEST = "GET_LIST_REQUEST";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
export const GET_LIST_FAIL = "GET_LIST_FAIL";

export const GET_LIST_BY_ID_REQUEST = "GET_LIST_BY_ID_REQUEST";
export const GET_LIST_BY_ID_SUCCESS = "GET_LIST_BY_ID_SUCCESS";
export const GET_LIST_BY_ID_FAIL = "GET_LIST_BY_ID_FAIL";

export const ADD_LIST_REQUEST = "ADD_LIST_REQUEST";
export const ADD_LIST_SUCCESS = "ADD_LIST_SUCCESS";
export const ADD_LIST_FAIL = "ADD_LIST_FAIL";

export const DELETE_LIST_REQUEST = "DELETE_LIST_REQUEST";
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";
export const DELETE_LIST_FAIL = "DELETE_LIST_FAIL";

export const STAR_LIST_REQUEST = "STAR_LIST_REQUEST";
export const STAR_LIST_SUCCESS = "STAR_LIST_SUCCESS";
export const STAR_LIST_FAIL = "STAR_LIST_FAIL";

export const UNSTAR_LIST_REQUEST = "UNSTAR_LIST_REQUEST";
export const UNSTAR_LIST_SUCCESS = "UNSTAR_LIST_SUCCESS";
export const UNSTAR_LIST_FAIL = "UNSTAR_LIST_FAIL";
