export const GET_LIST_REQUEST = "GET_LIST_REQUEST";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
export const GET_LIST_FAIL = "GET_LIST_FAIL";

export const GET_LIST_BY_ID_REQUEST = "GET_LIST_BY_ID_REQUEST";
export const GET_LIST_BY_ID_SUCCESS = "GET_LIST_BY_ID_SUCCESS";
export const GET_LIST_BY_ID_FAIL = "GET_LIST_BY_ID_FAIL";
